config/routes.rb
Articles::Application.routes.draw do
  root :to => "articles#index"
  resources :articles
  resources :categories  

end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
  
  
  attr_accessible :article, :title, :photo, :category_id
  
  belongs_to :category  
  has_attached_file :photo, :styles => { :small => "150x150>", :thumb => "100x100>" },
                    :url => "/assets/article_photos/:id/:style/:basename",
                    :path =>":rails_root/public/assets/article_photos/:id/:style/:basename"
  
  validates :category_id, presence: true
  validates :title, presence: true, length: { minimum: 5 }
  validates :article, presence: true, length: { maximum: 500 } 
  
  validates_attachment_size :photo, :less_than => 1.megabyte
  validates_attachment_content_type :photo, :content_type => ['image/jpeg','image/png'],
                                    :message => "Must be jpg or png"
  
  
  #simple method to search for records
  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      find(:all, :order => "id DESC")
    end
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :articles, dependent: :destroy
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.search(params[:search])
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:success] = "Article added successfully!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def show
    @article = Article.find(params[:id])
    #if users using older slug(url) redirect them to the new url
    if request.path != article_path(@article)
      redirect_to article_path(@article)
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:success] = "Update successfull!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def index
    @category = Category.all
  end
  
  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:success] = "Category Added!"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/edit.html.erb
<% if @article.errors.any? %>
  <p>The form contains <%= pluralize(@article.errors.count, "error") %></p>
  <% for error in @article.errors.full_messages %>
  <ul>
    <li><%= error %></li>
  </ul>
  <% end %>
<% end %>
<hr />
<%= link_to "Back", article_path(@article) %>
<hr />
<%= form_for @article , :html => { :multipart => true } do |f| %>
   <%= f.label :title %><br />
   <%= f.text_field :title %><br />
   
    <%= f.label :category %><br /><%= link_to "Add category", new_category_path %><br />
  	<%= f.select(:category_id, options_from_collection_for_select(Category.all, :id, :name)) %><br />
   
   <%= f.label :article %><br />
   <%= f.text_area :article %><br />
   
   <%= f.file_field :photo %><br />
   
   <%= f.submit "Update Article"%>
<% end %>

app/views/articles/index.html.erb
<h1>How to - Tips and Tricks (<%= @article.count %> articles)</h1>
<hr />
<table>
	<tr>
		<td width="250">
			<%= form_tag articles_path, :method => "get" do %>
 				<%= text_field_tag :search, params[:search] %>
  				<%= submit_tag "Search", name: nil %>
			<% end %>			
		</td>
	</tr>
</table>
<hr />
<% for article in @article %>
  <h3><%= link_to article.title, article_path(article) %></h3>
  <p>
  	<%= image_tag article.photo.url(:thumb),:align => "left", :style => "padding-right: 10px;" %>
  	Posted: <b><%= article.created_at %></b><br />
  	<%= article.article %>
  </p>
 <div class="clear"></div>
<% end %>

app/views/articles/new.html.erb
<h2>New Article</h2>
<% if @article.errors.any? %>
  <p>The form contains <%= pluralize(@article.errors.count, "error") %></p>
  <% for error in @article.errors.full_messages %>
  <ul>
    <li><%= error %></li>
  </ul>
  <% end %>
<% end %>
<hr />
<%= link_to "Back", articles_path %>
<hr />

<%= form_for @article, :html => { :multipart => true } do |f|%>
  <p>
  	<%= f.label :title %><br />
  	<%= f.text_field :title %>
  </p>
  <p>
  	<%= f.label :category %><%= link_to "Add category", new_category_path %><br />
  	<%= f.select(:category_id, options_from_collection_for_select(Category.all, :id, :name)) %>
  <p>
  	<%= f.label :article %><br />
  	<%= f.text_area :article %>
  </p>
  <p>
  	<%= f.file_field :photo %>
  </p>
  <p>
  	<%= f.submit "Post Article" %>
  </p>
<% end %>

app/views/articles/show.html.erb
<%= flash[:success] %>
<hr />
<%= link_to "All Articles", articles_path %> | <%= link_to "Edit Article", edit_article_path(@article) %> | 
<%= link_to "New Article", new_article_path %> | <%= link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
<h2><%= @article.title %></h2>
<p><%= image_tag @article.photo.url(:small) %><br /><%= @article.article %></p>
<p>Category: <%= @article.category.name %></p>

app/views/categories/index.html.erb
<h3>All Categories</h3>
<%= flash[:success] %>
<hr />
<%= link_to "Add New Category", new_category_path %>
<hr />
<ul>
<% for category in  @category %>
   <li><%= category.name %></li>
<% end %>
</ul>

app/views/categories/new.html.erb
<% if @category.errors.any? %>
  <p>The form contains <%= pluralize(@category.errors.count, "error") %></p>
    <ul>
  <% for error in @category.errors.full_messages %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>
<%= form_for @category do |f| %>
  <%= f.label :category %><br />
  <%= f.text_field :name %><br />
  <%= f.submit "Add Category" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="content">
	
<%= yield %>

</div>
</body>
</html>